#!/bin/bash
python train.py -m "model1" -f "experiment2"
python train.py -m "model2" -f "experiment2"
python train.py -m "model3" -f "experiment2"
python train.py -m "model4" -f "experiment2"
python train.py -m "model5" -f "experiment2"
python train.py -m "model6" -f "experiment2"
python train.py -m "model7" -f "experiment2"
python train.py -m "base1" -f "experiment2"
python train.py -m "base2" -f "experiment2"
python train.py -m "base3" -f "experiment2"
python train.py -m "base4" -f "experiment2"
python train.py -m "base5" -f "experiment2"